version: "3.4"

services:
  localdb:
    image: postgres:12.7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: metricsdbuser
      POSTGRES_DB:  testmetricsdb
    privileged: true

  metrics-api:
    image: metrics:latest
    build:
      context: .
      dockerfile: ./docker/deploy/Dockerfile
    volumes:
        - ./:/srv
        - ./docker/deploy:/etc/uwsgi/conf.d
    depends_on:
      - localdb
    ports:
      - "80:80"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: metricsdbuser
      SQLALCHEMY_DATABASE_URI: postgresql://metricsdbuser:password@localdb:5432/testmetricsdb

volumes:
  postgres_data:
